### ISSUE TITLE
[ISSUE] AssertionError

### ISSUE THREAD

**Issue by Meng-Gen** [Meng-Gen/StockCat#48]
2015-09-07 18:15:22,838 - stockcat.pipeline.state.assembler_state - INFO - assemble: {u'stock_symbol': u'1201', u'listing_date': datetime.date(1962, 2, 9)} (progress: 8/15)
Traceback (most recent call last):
  File "main.py", line 14, in <module>
    sys.exit(main())
  File "main.py", line 10, in main
    stock_cat.run()
  File "/Users/menggen/Documents/StockCat/stockcat/stock_cat.py", line 21, in run
    self.run_capital_increase_history()
  File "/Users/menggen/Documents/StockCat/stockcat/stock_cat.py", line 36, in run_capital_increase_history
    CapitalIncreaseHistoryPipeline().run()
  File "/Users/menggen/Documents/StockCat/stockcat/pipeline/state/state_machine.py", line 47, in run
    self.state_map[self.curr_state].run()
  File "/Users/menggen/Documents/StockCat/stockcat/pipeline/state/assembler_state.py", line 34, in run
    self.dao[str(entry)] = self.assembler.assemble(internal_entry)
  File "/Users/menggen/Documents/StockCat/stockcat/assembler/capital_increase_history_assembler.py", line 19, in assemble
    relative_html_object = self.__traverse_to_relative_html_object(html_object)
  File "/Users/menggen/Documents/StockCat/stockcat/assembler/capital_increase_history_assembler.py", line 31, in __traverse_to_relative_html_object
    assert len(relative_html_object_list) > 0, 'invalid base_xpath (table_tags)'
AssertionError: invalid base_xpath (table_tags)

**Comment by Meng-Gen** [comment]
```
<html><head><meta HTTP-EQUIV="Content-Type" CONTENT="text/html; charset=big5"><title>¨t²Î³q§i</title></head><body><!--HttpCode=-1 Url=/z/zc/zcb/zcb_1201.djhtm Data= --></body></html>
```

**Comment by Meng-Gen** [comment]
亂碼是系統通告(encoded in big5)
